export const Industries = [
  "Oil & Gas",
  "Oil & Gas Producers",
  "Exploration & Production",
  "Integrated Oil & Gas",
  "Oil Equipment, Services & Distribution",
  "Pipelines",
  "Alternative Energy",
  "Renewable Energy Equipment",
  "Basic Materials",
  "Chemicals",
  "Forestry & Paper",
  "Industrial Metals & Mining",
  "Mining",
  "Construction & Materials",
  "Industrial Goods & Services",
  "General Industrials",
  "Electronic & Electrical Equipment",
  "Electrical Components & Equipment",
  "Industrial Engineering",
  "Industrial Transportation",
  "Delivery Services",
  "Marine Transportation",
  "Railroads",
  "Transportation Services",
  "Trucking",
  "Support Services",
  "Consumer Goods",
  "Automobiles & Parts",
  "Food & Beverage",
  "Personal & Household Goods",
  "Consumer Electronics",
  "Health Care",
  "Health Care Equipment & Services",
  "Health Care Providers",
  "Medical Equipment",
  "Medical Supplies",
  "Biotechnology",
  "Consumer Services",
  "Retail",
  "Food & Drug Retailers",
  "Drug Retailers",
  "Food Retailers & Wholesalers",
  "General Retailers",
  "Broadcasting & Entertainment",
  "Media Agencies",
  "Publishing",
  "Travel & Leisure",
  "Airlines",
  "Hotels",
  "Recreational Services",
  "Restaurants & Bars",
  "Telecommunications",
  "Fixed Line Telecommunications",
  "Utilities",
  "Electricity",
  "Gas, Water & Multi-utilities",
  "Gas Distribution",
  "Multi-utilities",
  "Water",
  "Financials",
  "Real Estate",
  "Real Estate Investment & Services",
  "Financial Services",
  "Asset Managers",
  "Consumer Finance",
  "Specialty Finance",
  "Investment Services",
  "Mortgage Finance",
  "Technology",
  "Software & Computer Services",
  "Computer Services",
  "Technology Hardware & Equipment",
  "Computer Hardware",
  "Electronic Office Equipment",
  "Telecommunications Equipment",
  "Education",
  "Application Service Provider",
  "Outsourced IT Provider",
  "Charity",
  "Professional Services",
];

export const Contries = ["USA"];
export const States = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "DC",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
];
export const PaymentOptions = [
  {value: "insured_paid", label: "Insured Paid"},
  {value: "agent_paid", label: "Agent Paid"},
];
